#!/bin/sh

JSON_STRING='window.configs = { \
  "VUE_APP_LOCAL_MIRROR_NODE_MENU_NAME":"'"${VUE_APP_LOCAL_MIRROR_NODE_MENU_NAME}"'", \
  "VUE_APP_LOCAL_MIRROR_NODE_URL":"'"${VUE_APP_LOCAL_MIRROR_NODE_URL}"'", \
  "VUE_APP_PRODUCT_NAME":"'"${VUE_APP_PRODUCT_NAME}"'", \
  "VUE_APP_DOCUMENT_TITLE_SUFFIX":"'"${VUE_APP_DOCUMENT_TITLE_SUFFIX}"'", \
  "VUE_APP_META_DESCRIPTION":"'"${VUE_APP_META_DESCRIPTION}"'", \
  "VUE_APP_META_URL":"'"${VUE_APP_META_URL}"'", \
  "VUE_APP_SPONSOR_URL":"'"${VUE_APP_SPONSOR_UR}"'", \
  "VUE_APP_TERMS_OF_USE_URL":"'"${VUE_APP_TERMS_OF_USE_URL}"'", \
  "VUE_APP_ESTIMATOR_NOTICE":"'"${VUE_APP_ESTIMATOR_NOTICE}"'", \
  "VUE_APP_WALLET_CHOOSER_DISCLAIMER_POPUP":"'"${VUE_APP_WALLET_CHOOSER_DISCLAIMER_POPUP}"'", \
  "VUE_APP_ENABLE_STAKING":"'"${VUE_APP_ENABLE_STAKING}"'" \
}'

sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /app/index.html

nginx -g "daemon off;"