#!/bin/sh

JSON_STRING='window.configs = { \
  "VITE_APP_LOCAL_MIRROR_NODE_MENU_NAME":"'"${VITE_APP_LOCAL_MIRROR_NODE_MENU_NAME}"'", \
  "VITE_APP_LOCAL_MIRROR_NODE_URL":"'"${VITE_APP_LOCAL_MIRROR_NODE_URL}"'", \
  "VITE_APP_PRODUCT_NAME":"'"${VITE_APP_PRODUCT_NAME}"'", \
  "VITE_APP_DOCUMENT_TITLE_SUFFIX":"'"${VITE_APP_DOCUMENT_TITLE_SUFFIX}"'", \
  "VITE_APP_META_DESCRIPTION":"'"${VITE_APP_META_DESCRIPTION}"'", \
  "VITE_APP_META_URL":"'"${VITE_APP_META_URL}"'", \
  "VITE_APP_SPONSOR_URL":"'"${VITE_APP_SPONSOR_UR}"'", \
  "VITE_APP_TERMS_OF_USE_URL":"'"${VITE_APP_TERMS_OF_USE_URL}"'", \
  "VITE_APP_ESTIMATOR_NOTICE":"'"${VITE_APP_ESTIMATOR_NOTICE}"'", \
  "VITE_APP_WALLET_CHOOSER_DISCLAIMER_POPUP":"'"${VITE_APP_WALLET_CHOOSER_DISCLAIMER_POPUP}"'", \
  "VITE_APP_ENABLE_STAKING":"'"${VITE_APP_ENABLE_STAKING}"'" \
}'

sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /app/index.html

nginx -g "daemon off;"