{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "hedera-explorer.labels" . | nindent 4 }}
  name: {{ include "hedera-explorer.serviceAccountName" . }}
  namespace: {{ include "hedera-explorer.namespace" . }}
{{- end -}}
