apiVersion: v1
entries:
  hedera-explorer:
  - apiVersion: v2
    appVersion: 23.8.0
    created: "2024-09-19T22:19:19.704789736Z"
    description: Hedera Mirror Node Explorer for the Hedera Hashgraph DLT
    digest: cbfd8df96035f397bcd8a5546920670efc41183a5fa1c6e965de11ee30a25b96
    home: https://github.com/hashgraph/hedera-mirror-node-explorer
    name: hedera-explorer
    sources:
    - https://github.com/hashgraph/hedera-mirror-node-explorer
    urls:
    - https://hashgraph.github.io/hedera-mirror-node-explorer/charts/hedera-explorer-0.2.0.tgz
    version: 0.2.0
generated: "2024-09-19T22:19:19.703876275Z"
