apiVersion: v1
entries:
  hedera-explorer:
  - apiVersion: v2
    appVersion: 23.8.0
    created: "2024-10-23T21:30:14.984247674Z"
    description: Hedera Mirror Node Explorer for the Hedera Hashgraph DLT
    digest: ce9c757ecbd62986537e4e9878e77ed5e235dfb0c3aee6348d1c98362ada5fc4
    home: https://github.com/hashgraph/hedera-mirror-node-explorer
    name: hedera-explorer
    sources:
    - https://github.com/hashgraph/hedera-mirror-node-explorer
    urls:
    - https://hashgraph.github.io/hedera-mirror-node-explorer/charts/hedera-explorer-0.2.0.tgz
    version: 0.2.0
generated: "2024-10-23T21:30:14.982296471Z"
