x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:

  repository:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/repository:${TAG}
    container_name: repository-${TAG}
    environment:
      - SOURCIFY_SERVER=http://host.docker.internal:5555
      - SERVER_URL=http://localhost:5555
    volumes:
      - type: bind
        source: ./data
        target: /data
        read_only: true
    ports:
      - "${REPOSITORY_PORT}:80"

  server:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/server:${TAG}
    container_name: server-${TAG}
    environment:
      - NODE_ENV=development
    ports:
      - "${SERVER_PORT}:5555"
    volumes:
      - type: bind
        source: ./servers.yaml
        target: /home/app/services/server/dist/servers.yaml
      - type: bind
        source: ./sourcify-chains.json
        target: /home/app/services/server/dist/sourcify-chains.json
      - type: bind
        source: ./local.js
        target: /home/app/services/server/dist/config/local.js
      - type: bind
        source: ./data
        target: /tmp/sourcify/repository
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 30s
      timeout: 10s
      retries: 10

  ui:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/ui:${TAG}
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - type: bind
        source: ./ui-config.json
        target: /usr/share/nginx/html/config.json
    ports:
      - "${UI_PORT}:80"

  nginx-service:
    container_name: nginx-container
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificate:/etc/nginx/certificate
    ports:
      - "80:80"
      - "443:443"
