version: "3.7"
x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:

  repository:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify:repository-${TAG}
    container_name: repository-${TAG}
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
        read_only: true
      - type: bind
        source: ./config.json
        target: /redirects/config.json
    ports:
      - "${REPOSITORY_SERVER_EXTERNAL_PORT}:80"

  server:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify:server-${TAG}
    container_name: server-${TAG}
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
      - type: bind
        source: $SOLJSON_REPO_HOST
        target: $SOLJSON_REPO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 10

  ui:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify:ui-${TAG}
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - type: bind
        source: ./config.json
        target: /usr/share/nginx/html/config.json
    ports:
      - "${UI_EXTERNAL_PORT}:80"

  nginx-service:
    container_name: nginx-container
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificate:/etc/nginx/certificate
    ports:
      - "80:80"
      - "443:443"
