name: Helm Chart Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  chart:
    name: Publish charts
    runs-on: mirror-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: "v3.12.3" #  helm version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm package
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
          helm dependency update chart
          helm package chart

      - name: Build and Push the Helm Charts to GitHub Container Registry
        uses: JimCronqvist/action-helm-chart-repo@583db84dfb460a9dd462e2d7d803b82872b8978e # v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish helm chart to github pages
        uses: step-security/helm-gh-pages@e32a08830c96b9109c2f3daa9e60b657e63020e2 # v1.7.1
        with:
          charts_dir: .
          target_dir: charts
          token: ${{ secrets.GITHUB_TOKEN }}
