name: Helm Chart Release

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  chart:
    name: Publish charts
    runs-on: mirror-node-linux-medium
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Publish helm chart
        uses: step-security/helm-gh-pages@6a390e89293c1ec8bc5120f6692f3b8a313a9a3d # v1.7.0
        with:
          target_dir: charts
          token: ${{ secrets.GITHUB_TOKEN }}
