name: "ZXC: Release Helm Chart"

on:
  workflow_call:
    inputs:
      new-version:
        description: "New Release Version (ie. 0.30.0):"
        type: string
        required: true
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: true

permissions:
  id-token: write
  packages: write
  contents: read

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  chart:
    name: Chart
    runs-on: mirror-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: "v3.12.3" #  helm version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Update Helm Chart Version
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        env:
          relver: ${{ inputs.new-version }}
        with:
          cmd: yq '.version = strenv(relver) | .appVersion = strenv(relver)' -i chart/Chart.yaml

      - name: Show Helm Chart Manifest
        run: cat chart/Chart.yaml

      - name: Package Helm Chart
        run: helm package chart

      - name: Show Helm Chart Package
        run: ls -al *.tgz

      - name: Push Helm Chart
        if: ${{ inputs.dry-run-enabled != true }}
        run: helm push hedera-explorer-chart-${{ inputs.new-version }}.tgz oci://ghcr.io/hashgraph/hedera-mirror-node-explorer
