name: "ZXC: Compile Explorer Code"
on:
  workflow_call:
    inputs:
      enable-unit-tests:
        description: "Unit Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-e2e-tests:
        description: "E2E Testing Enabled"
        type: boolean
        required: false
        default: false
      enable-sonar-analysis:
        description: "Sonar Analysis Enabled"
        type: boolean
        required: false
        default: false
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Compiles"

    secrets:
      access-token:
        description: "The Github access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true
      sonar-token:
        description: "The SonarCloud access token used by the SonarQube agent to report an analysis."
        required: false

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write
  checks: write
  issues: read
  contents: read

env:
  LC_ALL: C.UTF-8

jobs:
  compile:
    name: ${{ inputs.custom-job-label || 'Compiles' }}
    runs-on: mirror-node-linux-large
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: npm

      - name: Setup Xvfb
        if: ${{ inputs.enable-e2e-tests && !cancelled() }}
        run: |
          if ! command -v xvfb-run >/dev/null 2>&1; then
            echo "::group::Updating Aptitude"
              sudo apt update
            echo "::endgroup::"
            echo "::group::Installing Xvfb"
              sudo apt install -y xvfb
            echo "::endgroup::"
          fi

      - name: Install Google Chrome
        if: ${{ inputs.enable-e2e-tests && !cancelled() }}
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Install Dependencies
        run: npm ci

      - name: Compile Code
        run: npm run build

      - name: Unit Tests
        run: npm run cover:unit
        if: ${{ inputs.enable-unit-tests && !cancelled() }}

      - name: Report Unit Test Coverage
        uses: step-security/vitest-coverage-report-action@aba564d7473e0398ae1f89a0f8987405608c1536 # v2.5.1
        if: ${{ inputs.enable-unit-tests && !cancelled() }}

      - name: Cypress run
        uses: cypress-io/github-action@7271bed2a170d73c0b08939cd192db51a1c46c50 # v6.7.10
        if: ${{ inputs.enable-e2e-tests && !cancelled() }}
        with:
          install-command: npm install
          browser: chrome
          start: npm run dev
          spec: tests/e2e/specs/*

      - name: Sonar Analysis
        uses: sonarsource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 # v3.1.0
        if: ${{ inputs.enable-sonar-analysis && !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
